### ISSUE TITLE
Collect information on "Paid Options" to download articles

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#369]
- [ ] Information on the various kinds of licenses (e.g. the various CC-*) need to be added in a new section of the page created for #353.
- [ ] The column "paid options" of the table created in #353 needs to be filled.
- [ ] Should there be also other article repositories (other than those identified in the table created for #353) that offer download options for money, they should also be documented and added to the table.

**Comment by pafonta** [comment]
## Review

As discussed, check the box if you are `happy` with the new content - the [page](https://bbpteam.epfl.ch/project/spaces/display/BBS/Database+Creation), the [diff](https://bbpteam.epfl.ch/project/spaces/pages/diffpagesbyversion.action?pageId=69912253&selectedPageVersions=27&selectedPageVersions=20) (green lines) - or `say` why not:
- [ ] @FrancescoCasalegno 
- [ ] @Stannislav 
- [ ] @EmilieDel 
- [ ] @jankrepl 

## Note

To know if the famous `publishers` offer a `paid option` to download their articles, I have ended up doing part of #370.

Indeed, I had a look at their licensing to see if they allow or provide dedicated services for Text and Data Mining.

The task of #370 that was done is:

> In particular, it is important to know what are the legal terms to (i) download (ii) re-use (iii) store the papers.

**Comment by Stannislav** [comment]
Just had a look - looks very useful. I'm wondering how much downloading from the S3 bucket for {bio}arXive would cost, do we have any estimate of price/GB?

**Comment by jankrepl** [comment]
Great job! Thank you for it!

**Comment by FrancescoCasalegno** [comment]
Awesome!
